name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["data"]
analysis-paths: ["analyses"]

models:
  my_dbt_project:
    +materialized: view
